# 	Analyzing socio-economic impacts of implementation of mitigation strategies in BC’s forest sector

**Zach Xu**

Economist, Climate Change

Canadian Forest Service, Natural Resources Canada

**Tony Lemprière**

Senior Manager, Climate Change Policy

Canadian Forest Service, Natural Resources Canada

**Jun Duan**

Policy Research Analyst

Department of Economics, UVic

# Table of contents
1. [Introduction](#introduction)
    1. [Objectives](#objective)
2. [Methodology](#method)    
3. [Results](#result)
4. [Reference](#ref)
5. [Platform setup](#setup)

## 1. Introduction <a name="introduction"></a>

The Forest Carbon Management Project funded by Pacific Institute for Climate Solutions (PICS Project) explores various strategies for climate change mitigation involving BC forest management and forest products. The project examines impacts of the strategies on greenhouse gas (GHG) emissions, economic indicators (cost per tonne of mitigation, industry net revenue) socio-economic indicators (jobs, GDP and government tax revenue). The spreadsheet based socio-economic analysis was developed in phase 1 of the project using the assessment of the economic impacts of mitigation strategies. Results and methodologies for Phase 1 are described in Xu et al. (2017), “Climate change mitigation strategies in the forest sector: biophysical impacts and economic implications in British Columbia, Canada” (Mitig Adapt Strateg Glob Change. DOI 10.1007/s11027-016-9735-7).


Phase 2 of the project is updating and refining the mitigation strategies. The model is going to migrate to a more advanced platform(Python) with updated parameters, and extending the scope of the model to include displacement effects.

### A. OBJECTIVES  <a name="objective"></a>

The objectives of this project are:
	
1. Migrate the existing spreadsheet model (to be provided by the Project Authority) to the Python platform with a user-friendly interface to make the model more automated and efficient. 

2. Update the input data and calculations (where necessary) to improve the analysis, for example by replacing national Input-Output coefficients with BC coefficients. Updates and improvements in data and calculations will be agreed with the Project Authority).

3. Extend the model to reflect impacts on jobs, GDP and government tax revenue from displacement effects of mitigation strategies.

In [9]:
# # only need to run once to install necessary packages for the computation
# # ctrl + / to uncomment the code below
# import sys
# !conda install --yes --prefix {sys.prefix} pandas xlrd openpyxl xlsxwriter
# or
# # Install a pip package in the current Jupyter kernel
# import sys
# !{sys.executable} -m pip install numpy pandas xlsxwriter xlrd openpyxl --user

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from io_helper import *

## 2. Methodology <a name="method"></a>


### 2.A. Input-Output Model.

#### 2.A.1 Two Types of Impacts

Two different types of impacts are calculated in an input-output analysis:

* The direct impact measures the impact on B.C. industries supplying goods and services directly used by the project. For example, direct impacts for a typical construction project would include impacts in industries supplying goods and services such as cement, lumber, or engineering.

* The indirect (supplier industry) impact measures the impact on B.C. industries that are further back in the supply chain. The indirect impact is cumulative, and includes transactions going all the way back to the beginning of the supply chain. Indirect impacts for a typical construction project would include impacts in industries supplying a wide range of goods and services, such as janitorial services, accounting, transportation, logging and mining.

#### 2.A.2 The Impacts on Output, GDP, Employment and Government Revenue

##### **Output**

Output measures the total value of industry production in British Columbia that is associated with a project. 

##### **Gross Domestic Product (GDP)**

GDP is a measure of the value added (the unduplicated total value of goods and services) to the British Columbia economy by current productive activities attributable to the project. GDP is calculated by subtracting the cost of purchased goods, services and energy from the total value of an industry's output. As a result, the value of the work done by a producing industry is only counted once.

##### **Employment**

The full-time equivalent estimates are calculated based on the assumption that a full-time employee works 35 hours a week, for 50 weeks of the year (a total of 1,750 hours a year).

##### **Tax revenues**

Government tax revenue estimates generated by the model include federal, provincial and local income and commodity taxes.

### 2.B Key Assumptions of Parameters


#### 2.B.1 Multipliers

Input-Output multipliers to assess the incremental effects of activities (and associated costs) at the projects on the economy in BC. These multipliers reflect average interdependencies between industries and the Province’s economy, based on the type of activity under analysis.

In [2]:
input_file = "data_input.xlsx"
output_file = "output_data.xlsx"
summary_file = "summary.xlsx"

In [3]:
multilpiers = pd.read_excel(input_file, sheet_name="multipliers", usecols= "A:J")
multilpiers

,code,industry,Direct Employment,Indirect Employment,Direct Output,Indirect Output,Direct GDP,Indirect GDP,Government Revenue,No.
0,BS321200,wood,3.790978,2.863013,1,0.703165,0.339511,0.302766,0.033155,64
1,BS322100,paper,1.437815,2.702983,1,0.743123,0.306143,0.338300,0.048205,66
2,BS331200,steel,2.727223,1.284748,1,0.282999,0.247850,0.143447,0.021913,83
3,BS484000,transportation,4.337452,2.363650,1,0.493081,0.376299,0.229157,0.088737,154
4,BS221100,electricity,1.487445,1.263812,1,0.214218,0.781195,0.120363,0.118400,36
5,BS23B000,construction,4.167286,2.572674,1,0.421131,0.440600,0.228357,0.056539,40
6,BS113000,harvest,2.569630,3.077077,1,0.585512,0.342792,0.276596,0.047723,18
7,BS221100,bioenergy,1.487445,1.263812,1,0.214218,0.781195,0.120363,0.118400,36
8,BS115300,residue_extraction,6.912455,1.480911,1,0.308093,0.497453,0.145420,0.050347,21
9,BS326100,plastic,3.729603,1.425589,1,0.275888,0.386044,0.143010,0.033002,65
10,BS327300,concrete,2.759328,1.429805,1,0.512055,0.380721,0.257660,0.035110,81

#### 2.B.1 Unit Labor

In [4]:
unit_labor = pd.read_excel(input_file, sheet_name="unit-labor", usecols= "A:C")
unit_labor

             industry  unit_labor                                    comment
0             harvest    0.000171             Unit Labor for Harvest (PY/m3)
1             residue    0.000240            Unit Labor for Residue (PY/odt)
2                wood    0.000387    Unit Labor for wood manufacture (PY/m3)
3               paper    0.000272  Unit Labor for paper manufacture (PY/odt)
4           bioenergy    0.000085          Unit Labor for Bioenergy (PY/odt)
5  residue_extraction    0.000240            Unit Labor for Residue (PY/odt)

#### 2.B.3 Parameters

In [5]:
parameters = pd.read_excel(input_file, sheet_name="parameters", usecols= "A:B")

In [6]:
parameters

                parameter   value
0                discount    0.03
1  subs_sawnwood_concrete    3.46
2     subs_panel_concrete    3.89
3   subs_sawnwood_plastic    0.59
4      subs_panel_plastic    0.85
5  weight_per_m3_concrete    2.50
6   price_per_m3_concrete  200.00
7   weight_per_m3_plastic     NaN
8    price_per_m3_plastic     NaN

## 3. Results <a name="result"></a>

### 3.1 Scanario1:  FM1 Higher utilization

[FM1 Higher utilization](./01FM1.ipynb)

In [7]:
strategy_name = "FM1"

# specify input data by select the sheets names in the Excel file
input_sheet_name = "FM1-BASE-INPUT"
output_sheet_name = 'FM1-BASE-OUTPUT'
# regular multipliers
multipliers_sheet = 'multipliers'
# regular parameters                 
parameters_sheet = 'parameters'
# regular unit labor
unitlabor_sheet = "unit-labor"

# myFM1= FM1(input_file, input_sheet_name, output_file ,output_sheet_name, multipliers_sheet, 
#                  parameters_sheet, unitlabor_sheet)

In [8]:
myFM1 = Strategy(strategy_name, input_file, input_sheet_name, output_file, output_sheet_name, multipliers_sheet, 
                 parameters_sheet, unitlabor_sheet)

In [9]:
myFM1.find_final_result()

Return a table with all impacts and summary,
                 and please check out the table for detail...
Return a dictionary with industry objects, and please check out the .['bioenergy'] or . [residue_extraction] for detail...

,year,direct_employment,indirect_employment,total_employment,direct_output,indirect_output,total_output,direct_GDP,indirect_GDP,total_GDP,government_revenue
0,2016.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
1,2017.000000,128.145108,253.274371,381.419479,-1.563806e+08,-1.221054e+08,-2.784860e+08,-4.265310e+07,-5.839316e+07,-1.010463e+08,-9.944007e+06
2,2018.000000,128.542266,254.059340,382.601606,-1.501413e+08,-1.176546e+08,-2.677959e+08,-4.080040e+07,-5.627203e+07,-9.707243e+07,-9.581453e+06
3,2019.000000,128.939433,254.844328,383.783761,-1.484779e+08,-1.159035e+08,-2.643814e+08,-4.050887e+07,-5.542673e+07,-9.593560e+07,-9.438941e+06
4,2020.000000,129.336583,255.629281,384.965864,-1.434003e+08,-1.121734e+08,-2.555737e+08,-3.903982e+07,-5.364703e+07,-9.268685e+07,-9.135123e+06
5,2021.000000,294.886843,582.833641,877.720484,-3.205896e+08,-2.501561e+08,-5.707458e+08,-8.750144e+07,-1.196266e+08,-2.071280e+08,-2.037222e+07
6,2022.000000,294.886845,582.833645,877.720490,-3.048896e+08,-2.391447e+08,-5.440343e+08,-8.277185e+07,-1.143825e+08,-1.971543e+08,-1.947522e+07
7,2023.000000,294.886842,582.833640,877.720483,-3.026099e+08,-2.360441e+08,-5.386539e+08,-8.262364e+07,-1.128766e+08,-1.955003e+08,-1.922298e+07
8,2024.000000,294.886842,582.833639,877.720481,-2.892760e+08,-2.265225e+08,-5.157985e+08,-7.866772e+07,-1.083388e+08,-1.870065e+08,-1.844738e+07
9,2025.000000,294.886840,582.833636,877.720477,-2.891364e+08,-2.247763e+08,-5.139127e+08,-7.921678e+07,-1.074751e+08,-1.866919e+08,-1.830551e+07
10,2026.000000,294.886840,582.833637,877.720477,-2.706359e+08,-2.123279e+08,-4.829638e+08,-7.345444e+07,-1.015569e+08,-1.750114e+08,-1.729133e+07
11,2027.000000,294.886842,582.833640,877.720482,-2.559322e+08,-2.021498e+08,-4.580820e+08,-6.897679e+07,-9.671227e+07,-1.656891e+08,-1.646217e+07
12,2028.000000,294.886842,582.833640,877.720483,-2.554950e+08,-2.003706e+08,-4.558655e+08,-6.937317e+07,-9.583632e+07,-1.652095e+08,-1.631757e+07
13,2029.000000,294.886841,582.833638,877.720480,-2.525257e+08,-1.971531e+08,-4.496789e+08,-6.888568e+07,-9.428200e+07,-1.631677e+08,-1.605574e+07
14,2030.000000,294.886843,582.833641,877.720484,-2.432573e+08,-1.902905e+08,-4.335478e+08,-6.622341e+07,-9.100670e+07,-1.572301e+08,-1.549679e+07
15,2031.000000,277.633481,548.732970,826.366451,-2.343051e+08,-1.809362e+08,-4.152413e+08,-6.462951e+07,-8.649205e+07,-1.511216e+08,-1.473548e+07
16,2032.000000,277.633482,548.732972,826.366454,-2.112982e+08,-1.661912e+08,-3.774894e+08,-5.719989e+07,-7.949687e+07,-1.366968e+08,-1.353401e+07
17,2033.000000,277.633480,548.732967,826.366447,-2.043874e+08,-1.609078e+08,-3.652952e+08,-5.527456e+07,-7.697219e+07,-1.322467e+08,-1.310372e+07
18,2034.000000,277.633482,548.732971,826.366453,-2.106818e+08,-1.633921e+08,-3.740739e+08,-5.786293e+07,-7.811786e+07,-1.359808e+08,-1.330654e+07
19,2035.000000,277.633482,548.732971,826.366453,-1.959622e+08,-1.536076e+08,-3.495698e+08,-5.323535e+07,-7.346850e+07,-1.267038e+08,-1.250935e+07
20,2036.000000,277.633482,548.732970,826.366452,-1.907257e+08,-1.494094e+08,-3.401351e+08,-5.184630e+07,-7.145895e+07,-1.233052e+08,-1.216749e+07
21,2037.000000,277.633481,548.732969,826.366450,-1.893337e+08,-1.474952e+08,-3.368289e+08,-5.176330e+07,-7.052913e+07,-1.222924e+08,-1.201177e+07
22,2038.000000,277.633482,548.732970,826.366452,-1.813276e+08,-1.417404e+08,-3.230680e+08,-4.940156e+07,-6.778573e+07,-1.171873e+08,-1.154301e+07
23,2039.000000,277.633482,548.732970,826.366452,-1.745170e+08,-1.367167e+08,-3.112337e+08,-4.743847e+07,-6.538841e+07,-1.128269e+08,-1.113383e+07
24,2040.000000,277.633481,548.732968,826.366449,-1.742639e+08,-1.355626e+08,-3.098265e+08,-4.771242e+07,-6.481983e+07,-1.125323e+08,-1.104004e+07
25,2041.000000,275.557142,544.629157,820.186299,-1.576266e+08,-1.246013e+08,-2.822279e+08,-4.244680e+07,-5.961330e+07,-1.020601e+08,-1.014695e+07
26,2042.000000,275.557141,544.629155,820.186297,-1.663664e+08,-1.287775e+08,-2.951438e+08,-4.578020e+07,-6.156425e+07,-1.073444e+08,-1.048760e+07
27,2043.000000,275.557142,544.629156,820.186298,-1.529362e+08,-1.200003e+08,-2.729365e+08,-4.150408e+07,-5.739666e+07,-9.890074e+07,-9.772452e+06
28,2044.000000,275.557142,544.629157,820.186299,-1.461851e+08,-1.151605e+08,-2.613456e+08,-3.950796e+07,-5.508968e+07,-9.459765e+07,-9.378216e+06
29,2045.000000,275.557143,544.629158,820.186300,-1.446300e+08,-1.133888e+08,-2.580188e+08,-3.928371e+07,-5.423269e+07,-9.351640e+07,-9.234046e+06
30,2046.000000,275.557141,544.629155,820.186297,-1.480750e+08,-1.145698e+08,-2.626448e+08,-4.076447e+07,-5.477114e+07,-9.553562e+07,-9.330537e+06
31,2047.000000,275.557141,544.629154,820.186294,-1.346915e+08,-1.059218e+08,-2.406133e+08,-3.646780e+07,-5.066695e+07,-8.713476e+07,-8.625891e+06
32,2048.000000,275.557141,544.629154,820.186295,-1.276568e+08,-1.010148e+08,-2.286716e+08,-3.433899e+07,-4.833055e+07,-8.266954e+07,-8.226153e+06
33,2049.000000,275.557141,544.629155,820.186297,-1.293481e+08,-1.012399e+08,-2.305879e+08,-3.519313e+07,-4.841909e+07,-8.361221e+07,-8.244712e+06
34,2050.000000,275.557142,544.629157,820.186299,-1.330056e+08,-1.026385e+08,-2.356441e+08,-3.671329e+07,-4.906252e+07,-8.577581e+07,-8.358917e+06
sum,69139.000000,8995.738042,17779.764975,26775.503016,-6.790071e+09,-5.310045e+09,-1.210012e+10,-1.849062e+09,-2.539509e+09,-4.388571e+09,-4.324371e+08
mean,2033.500000,264.580531,522.934264,787.514795,-1.997080e+08,-1.561778e+08,-3.558858e+08,-5.438417e+07,-7.469144e+07,-1.290756e+08,-1.271874e+07
std,9.958246,51.021044,100.841327,151.862371,5.881459e+07,4.595636e+07,1.047658e+08,1.603680e+07,2.197795e+07,3.800683e+07,3.742580e+06
max,2050.000000,294.886845,582.833645,877.720490,-1.276568e+08,-1.010148e+08,-2.286716e+08,-3.433899e+07,-4.833055e+07,-8.266954e+07,-8.226153e+06
min,2017.000000,128.145108,253.274371,381.419479,-3.205896e+08,-2.501561e+08,-5.707458e+08,-8.750144e+07,-1.196266e+08,-2.071280e+08,-2.037222e+07

In [11]:
myFM1.find_output_summary()

Return a table only with summary,
         and please check out the table for detail...
Return a table with all impacts and summary,
                 and please check out the table for detail...
Return a dictionary with industry objects, and please check out the .['bioenergy'] or . [residue_extraction] for detail...

,direct_employment,indirect_employment,total_employment,direct_output,indirect_output,total_output,direct_GDP,indirect_GDP,total_GDP,government_revenue
sum,8995.738042,17779.764975,26775.503016,-6.790071e+09,-5.310045e+09,-1.210012e+10,-1.849062e+09,-2.539509e+09,-4.388571e+09,-4.324371e+08
mean,264.580531,522.934264,787.514795,-1.997080e+08,-1.561778e+08,-3.558858e+08,-5.438417e+07,-7.469144e+07,-1.290756e+08,-1.271874e+07
std,51.021044,100.841327,151.862371,5.881459e+07,4.595636e+07,1.047658e+08,1.603680e+07,2.197795e+07,3.800683e+07,3.742580e+06
max,294.886845,582.833645,877.720490,-1.276568e+08,-1.010148e+08,-2.286716e+08,-3.433899e+07,-4.833055e+07,-8.266954e+07,-8.226153e+06
min,128.145108,253.274371,381.419479,-3.205896e+08,-2.501561e+08,-5.707458e+08,-8.750144e+07,-1.196266e+08,-2.071280e+08,-2.037222e+07

### 3.2 Scanario2:  FM2 Harvest less

[FM2 Harvest less](./02FM2Class.ipynb)

In [18]:
# input data for computation
input_file = "data_input.xlsx"
# output data for reporting
output_file = "output_data.xlsx"



# specify input data by select the sheets names in the Excel file
input_sheet_name = "FM2-BASE-INPUT"
output_sheet_name = 'FM2-BASE-OUTPUT'
# regular multipliers
multipliers_sheet = 'multipliers'
# regular parameters                 
parameters_sheet = 'parameters'
# regular unit labor
unitlabor_sheet = "unit-labor"

In [19]:
myFM2 = Strategy(strategy_name, input_file, input_sheet_name, output_file, output_sheet_name, multipliers_sheet, 
                 parameters_sheet, unitlabor_sheet)

In [15]:
myFM2.find_final_result()

Return a table with all impacts and summary,
                 and please check out the table for detail...
Return a dictionary with industry objects, and please check out the .['concrete'] or . [harvest] for detail...
Return a concrete industry object with all impacts, and please check out the .full_table for detail...
Return a wood foresty object with all impacts, and please check out the .full_table for detail...
Return a paper foresty object with all impacts, and please check out the .full_table for detail...
Return a harvest foresty object with all impacts, and please check out the .full_table for detail...

,year,direct_employment,indirect_employment,total_employment,direct_output,indirect_output,total_output,direct_GDP,indirect_GDP,total_GDP,government_revenue
0,2016.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
1,2017.000000,0.707327,-243.284773,-242.577446,-2.509446e+08,-8.295345e+07,-1.572546e+08,-1.342188e+07,-3.365227e+07,-4.707414e+07,-5.355131e+06
2,2018.000000,0.709444,-244.038744,-243.329300,-2.436929e+08,-7.773111e+07,-1.442332e+08,-1.086975e+07,-3.124943e+07,-4.211919e+07,-4.999971e+06
3,2019.000000,0.711646,-244.792825,-244.081179,-2.383890e+08,-7.366707e+07,-1.343177e+08,-8.981584e+06,-2.939190e+07,-3.837349e+07,-4.737495e+06
4,2020.000000,0.713865,-245.546771,-244.832907,-2.317338e+08,-6.882939e+07,-1.222775e+08,-6.626709e+06,-2.716708e+07,-3.379379e+07,-4.410281e+06
5,2021.000000,0.651033,-223.938356,-223.287323,-2.058391e+08,-5.889743e+07,-1.021401e+08,-4.290789e+06,-2.301417e+07,-2.730496e+07,-3.769202e+06
6,2022.000000,0.651046,-223.938305,-223.287259,-1.988685e+08,-5.418164e+07,-9.045372e+07,-2.030690e+06,-2.085275e+07,-2.288344e+07,-3.445861e+06
7,2023.000000,0.651082,-223.938245,-223.287163,-1.945718e+08,-5.104998e+07,-8.302546e+07,-6.834453e+05,-1.943775e+07,-2.012120e+07,-3.249861e+06
8,2024.000000,0.651003,-223.938268,-223.287265,-1.884764e+08,-4.688305e+07,-7.276317e+07,1.284060e+06,-1.753182e+07,-1.624776e+07,-2.967753e+06
9,2025.000000,0.650783,-223.938413,-223.287630,-1.862006e+08,-4.496995e+07,-6.857427e+07,1.945799e+06,-1.668877e+07,-1.474297e+07,-2.867673e+06
10,2026.000000,0.651116,-223.938182,-223.287066,-1.758015e+08,-3.831746e+07,-5.152262e+07,5.395611e+06,-1.360506e+07,-8.209449e+06,-2.379671e+06
11,2027.000000,0.650857,-223.938367,-223.287510,-1.731560e+08,-3.622124e+07,-4.678095e+07,6.190863e+06,-1.267203e+07,-6.481162e+06,-2.261460e+06
12,2028.000000,0.651070,-223.938241,-223.287171,-1.658247e+08,-3.139736e+07,-3.462576e+07,8.595638e+06,-1.044877e+07,-1.853133e+06,-1.919391e+06
13,2029.000000,0.651115,-223.938227,-223.287112,-1.626385e+08,-2.901592e+07,-2.905804e+07,9.582686e+06,-9.377707e+06,2.049786e+05,-1.774909e+06
14,2030.000000,0.651096,-223.938274,-223.287178,-1.592883e+08,-2.655353e+07,-2.324548e+07,1.062898e+07,-8.266836e+06,2.362145e+06,-1.622385e+06
15,2031.000000,0.612919,-210.836039,-210.223120,-1.501756e+08,-2.466336e+07,-2.175588e+07,9.842784e+06,-7.672022e+06,2.170762e+06,-1.544066e+06
16,2032.000000,0.612897,-210.836018,-210.223121,-1.337425e+08,-1.459711e+07,4.743492e+06,1.538530e+07,-2.963192e+06,1.242211e+07,-7.663510e+05
17,2033.000000,0.613044,-210.835883,-210.222839,-1.405487e+08,-1.815074e+07,-5.616389e+06,1.296419e+07,-4.687043e+06,8.277143e+06,-1.097507e+06
18,2034.000000,0.612778,-210.836215,-210.223437,-1.333521e+08,-1.351808e+07,6.212937e+06,1.534573e+07,-2.542371e+06,1.280336e+07,-7.602127e+05
19,2035.000000,0.613013,-210.835957,-210.222944,-1.245842e+08,-7.977662e+06,2.052121e+07,1.826834e+07,3.240129e+04,1.830074e+07,-3.477559e+05
20,2036.000000,0.612928,-210.836013,-210.223084,-1.284752e+08,-9.860971e+06,1.474694e+07,1.685403e+07,-8.985612e+05,1.595547e+07,-5.392462e+05
21,2037.000000,0.612978,-210.835946,-210.222968,-1.222572e+08,-5.836919e+06,2.498891e+07,1.890730e+07,9.623190e+05,1.986962e+07,-2.481382e+05
22,2038.000000,0.612932,-210.836026,-210.223094,-1.177281e+08,-2.812806e+06,3.254222e+07,2.038398e+07,2.351996e+06,2.273597e+07,-3.745813e+04
23,2039.000000,0.612921,-210.836027,-210.223106,-1.176446e+08,-2.402537e+06,3.303598e+07,2.033891e+07,2.508025e+06,2.284694e+07,-3.878198e+04
24,2040.000000,0.613060,-210.835866,-210.222806,-1.072267e+08,4.048069e+06,4.990439e+07,2.383851e+07,5.518611e+06,2.935712e+07,4.532371e+05
25,2041.000000,0.608169,-209.259339,-208.651170,-1.088405e+08,2.941500e+06,4.603924e+07,2.276323e+07,4.933550e+06,2.769678e+07,3.295987e+05
26,2042.000000,0.608729,-209.258814,-208.650085,-1.072072e+08,4.226015e+06,4.895698e+07,2.325615e+07,5.506037e+06,2.876219e+07,4.027200e+05
27,2043.000000,0.607904,-209.259588,-208.651684,-1.002588e+08,8.613061e+06,6.029243e+07,2.557304e+07,7.545163e+06,3.311820e+07,7.296394e+05
28,2044.000000,0.608305,-209.259275,-208.650971,-9.439998e+07,1.235290e+07,6.989115e+07,2.751833e+07,9.279517e+06,3.679784e+07,1.004700e+06
29,2045.000000,0.608524,-209.259149,-208.650625,-9.892360e+07,1.000467e+07,6.301934e+07,2.590643e+07,8.138808e+06,3.404524e+07,7.844061e+05
30,2046.000000,0.608001,-209.259456,-208.651455,-9.493724e+07,1.263033e+07,6.963127e+07,2.721342e+07,9.348677e+06,3.656210e+07,9.703611e+05
31,2047.000000,0.608532,-209.259006,-208.650475,-9.006861e+07,1.576411e+07,7.763368e+07,2.882461e+07,1.079947e+07,3.962409e+07,1.198549e+06
32,2048.000000,0.608793,-209.258806,-208.650013,-8.324684e+07,2.003324e+07,8.872458e+07,3.110701e+07,1.278747e+07,4.389448e+07,1.520069e+06
33,2049.000000,0.608083,-209.259455,-208.651371,-8.725081e+07,1.795578e+07,8.264320e+07,2.968008e+07,1.177818e+07,4.145826e+07,1.325067e+06
34,2050.000000,0.608434,-209.259172,-208.650738,-8.685022e+07,1.844945e+07,8.353747e+07,2.976457e+07,1.198430e+07,4.174886e+07,1.340379e+06
sum,69139.000000,21.565425,-7417.998040,-7396.432614,-5.003145e+09,-6.934697e+08,-3.105795e+08,4.404547e+08,-1.886450e+08,2.518097e+08,-4.108184e+07
mean,2033.500000,0.634277,-218.176413,-217.542136,-1.471513e+08,-2.039617e+07,-9.134690e+06,1.295455e+07,-5.548383e+06,7.406168e+06,-1.208289e+06
std,9.958246,0.033658,11.576929,11.543272,4.993926e+07,3.058604e+07,7.274970e+07,1.308334e+07,1.377031e+07,2.684956e+07,2.029737e+06
max,2050.000000,0.713865,-209.258806,-208.650013,-8.324684e+07,2.003324e+07,8.872458e+07,3.110701e+07,1.278747e+07,4.389448e+07,1.520069e+06
min,2017.000000,0.607904,-245.546771,-244.832907,-2.509446e+08,-8.295345e+07,-1.572546e+08,-1.342188e+07,-3.365227e+07,-4.707414e+07,-5.355131e+06

In [16]:
myFM2.find_output_summary()

Return a table only with summary,
         and please check out the table for detail...
Return a table with all impacts and summary,
                 and please check out the table for detail...
Return a dictionary with industry objects, and please check out the .['concrete'] or . [harvest] for detail...
Return a concrete industry object with all impacts, and please check out the .full_table for detail...
Return a wood foresty object with all impacts, and please check out the .full_table for detail...
Return a paper foresty object with all impacts, and please check out the .full_table for detail...
Return a harvest foresty object with all impacts, and please check out the .full_table for detail...

,direct_employment,indirect_employment,total_employment,direct_output,indirect_output,total_output,direct_GDP,indirect_GDP,total_GDP,government_revenue
sum,21.565425,-7417.998040,-7396.432614,-5.003145e+09,-6.934697e+08,-3.105795e+08,4.404547e+08,-1.886450e+08,2.518097e+08,-4.108184e+07
mean,0.634277,-218.176413,-217.542136,-1.471513e+08,-2.039617e+07,-9.134690e+06,1.295455e+07,-5.548383e+06,7.406168e+06,-1.208289e+06
std,0.033658,11.576929,11.543272,4.993926e+07,3.058604e+07,7.274970e+07,1.308334e+07,1.377031e+07,2.684956e+07,2.029737e+06
max,0.713865,-209.258806,-208.650013,-8.324684e+07,2.003324e+07,8.872458e+07,3.110701e+07,1.278747e+07,4.389448e+07,1.520069e+06
min,0.607904,-245.546771,-244.832907,-2.509446e+08,-8.295345e+07,-1.572546e+08,-1.342188e+07,-3.365227e+07,-4.707414e+07,-5.355131e+06

### 3.3 Scanario3:  FM3 Harvest residues for bioenergyigher


[FM3 Harvest residues for bioenergyigher](./03FM3Class.ipynb)

In [20]:
strategy_name = "FM3"

# input data for computation
input_file = "data_input.xlsx"
# output data for reporting
output_file = "output_data.xlsx"

# specify input data by select the sheets names in the Excel file
input_sheet_name=  "FM3-BASE-INPUT"
output_sheet_name = 'FM3-BASE-OUTPUT'

# regular multipliers
multipliers_sheet = 'multipliers'
# regular parameters                 
parameters_sheet = 'parameters'
# regular unit labor
unitlabor_sheet = "unit-labor"

In [21]:
myFM3 = Strategy(strategy_name, input_file, input_sheet_name, output_file, output_sheet_name, multipliers_sheet, 
                 parameters_sheet, unitlabor_sheet)

In [5]:
myFM3.find_final_result()

Return a table with all impacts and summary,
                 and please check out the table for detail...
Return a dictionary with industry objects, and please check out the .['bioenergy'] or . [residue_extraction] for detail...

,year,direct_employment,indirect_employment,total_employment,direct_output,indirect_output,total_output,direct_GDP,indirect_GDP,total_GDP,government_revenue
0,2016.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2017.000000,322.570946,4159.988954,4482.559899,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2018.000000,357.506712,4201.665162,4559.171874,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2019.000000,397.622660,4342.501369,4740.124029,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2020.000000,426.616102,4378.914527,4805.530629,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,2021.000000,1033.577326,10008.301678,11041.879004,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,2022.000000,1105.869663,10119.391800,11225.261464,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,2023.000000,1155.069108,10113.417388,11268.486496,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,2024.000000,1190.092878,10021.415017,11211.507894,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,2025.000000,1267.994576,10224.494919,11492.489495,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,2026.000000,1291.943535,10109.415427,11401.358961,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,2027.000000,1373.882780,10324.980085,11698.862865,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,2028.000000,1436.453452,10426.585654,11863.039106,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,2029.000000,1488.447903,10505.458204,11993.906107,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,2030.000000,1556.476487,10676.080972,12232.557459,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,2031.000000,1558.440367,10342.407717,11900.848085,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,2032.000000,1579.960854,10238.585497,11818.546351,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,2033.000000,1638.925434,10350.512657,11989.438090,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,2034.000000,1722.551316,10608.426840,12330.978157,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,2035.000000,1778.885642,10768.029429,12546.915070,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,2036.000000,1780.207180,10593.407837,12373.615017,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21,2037.000000,1825.706201,10644.143765,12469.849967,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,2038.000000,1915.772261,10937.449917,12853.222178,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23,2039.000000,1971.569923,11052.948480,13024.518403,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24,2040.000000,2001.093969,11056.526794,13057.620763,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25,2041.000000,1986.637209,10835.791163,12822.428372,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26,2042.000000,2056.403355,11047.676132,13104.079488,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,2043.000000,2109.302380,11174.568491,13283.870870,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28,2044.000000,2117.228120,11092.885366,13210.113486,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29,2045.000000,2156.338909,11162.006731,13318.345641,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30,2046.000000,2178.970986,11168.386564,13347.357551,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31,2047.000000,2251.110602,11398.878639,13649.989241,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32,2048.000000,2379.595921,11849.518853,14229.114773,0.0,0.0,0.0,0.0,0.0,0.0,0.0
33,2049.000000,2346.584753,11600.916797,13947.501550,0.0,0.0,0.0,0.0,0.0,0.0,0.0
34,2050.000000,2369.492490,11611.936598,13981.429088,0.0,0.0,0.0,0.0,0.0,0.0,0.0
sum,69139.000000,54128.902000,339147.615422,393276.517422,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mean,2033.500000,1592.026529,9974.929865,11566.956395,0.0,0.0,0.0,0.0,0.0,0.0,0.0
std,9.958246,589.496554,2168.307766,2702.986271,0.0,0.0,0.0,0.0,0.0,0.0,0.0
max,2050.000000,2379.595921,11849.518853,14229.114773,0.0,0.0,0.0,0.0,0.0,0.0,0.0
min,2017.000000,322.570946,4159.988954,4482.559899,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:
myFM3.find_output_summary()

Return a table only with summary,
         and please check out the table for detail...
Return a table with all impacts and summary,
                 and please check out the table for detail...
Return a dictionary with industry objects, and please check out the .['bioenergy'] or . [residue_extraction] for detail...

,direct_employment,indirect_employment,total_employment,direct_output,indirect_output,total_output,direct_GDP,indirect_GDP,total_GDP,government_revenue
sum,54128.902000,339147.615422,393276.517422,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mean,1592.026529,9974.929865,11566.956395,0.0,0.0,0.0,0.0,0.0,0.0,0.0
std,589.496554,2168.307766,2702.986271,0.0,0.0,0.0,0.0,0.0,0.0,0.0
max,2379.595921,11849.518853,14229.114773,0.0,0.0,0.0,0.0,0.0,0.0,0.0
min,322.570946,4159.988954,4482.559899,0.0,0.0,0.0,0.0,0.0,0.0,0.0

### 3.4 Scanario4:  FM4 Restricted harvest 

[FM4 Restricted harvest ](./04FM4.ipynb)

In [12]:
strategy_name = "FM4"

# input data for computation
input_file = "data_input.xlsx"
# output data for reporting
output_file = "output_data.xlsx"

# specify input data by select the sheets names in the Excel file
input_sheet_name=  "FM4-BASE-INPUT"
output_sheet_name = 'FM4-BASE-OUTPUT'

# regular multipliers
multipliers_sheet = 'multipliers'
# regular parameters                 
parameters_sheet = 'parameters'
# regular unit labor
unitlabor_sheet = "unit-labor"

In [13]:
myFM4 = Strategy(strategy_name, input_file, input_sheet_name, output_file, output_sheet_name, multipliers_sheet, 
                 parameters_sheet, unitlabor_sheet)

In [16]:
myFM4.find_output_summary()

Return a table only with summary,
         and please check out the table for detail...
Return a table with all impacts and summary,
                 and please check out the table for detail...
Return a dictionary with industry objects, and please check out the .['bioenergy'] or . [residue_extraction] for detail...

,direct_employment,indirect_employment,total_employment,direct_output,indirect_output,total_output,direct_GDP,indirect_GDP,total_GDP,government_revenue
sum,-44964.556348,-46090.806305,-91055.362653,-1.417409e+10,-9.722240e+09,-2.389633e+10,-4.568579e+09,-4.444000e+09,-9.012580e+09,-6.555294e+08
mean,-1322.486951,-1355.611950,-2678.098902,-4.168850e+08,-2.859482e+08,-7.028333e+08,-1.343700e+08,-1.307059e+08,-2.650759e+08,-1.928028e+07
std,622.561805,638.155419,1260.717224,1.797924e+08,1.231550e+08,3.029466e+08,5.798511e+07,5.630855e+07,1.142931e+08,8.317604e+06
max,0.000054,0.000055,0.000109,1.011363e+06,5.921679e+05,1.603531e+06,3.466865e+05,2.797401e+05,6.264266e+05,4.826560e+04
min,-2113.613216,-2166.553943,-4280.167159,-6.840876e+08,-4.693305e+08,-1.153418e+09,-2.204733e+08,-2.145200e+08,-4.349933e+08,-3.163645e+07

### 3.5 Scanario5: HWP1 Longer-lived wood products

[HWP1](./05HWP1.ipynb)

In [14]:
strategy_name = "HWP1"

# input data for computation
input_file = "data_input.xlsx"
# output data for reporting
output_file = "output_data.xlsx"

# specify input data by select the sheets names in the Excel file
input_sheet_name=  "HWP1-BASE-INPUT"
output_sheet_name = 'HWP1-BASE-OUTPUT'

# regular multipliers
multipliers_sheet = 'multipliers'
# regular parameters                 
parameters_sheet = 'parameters'
# regular unit labor
unitlabor_sheet = "unit-labor"

In [15]:
myHWP1 = Strategy(strategy_name, input_file, input_sheet_name, output_file, output_sheet_name, multipliers_sheet, 
                 parameters_sheet, unitlabor_sheet)

In [17]:
myHWP1.find_output_summary()

Return a table only with summary,
         and please check out the table for detail...
Return a table with all impacts and summary,
                 and please check out the table for detail...
Return a dictionary with industry objects, and please check out the .['bioenergy'] or . [residue_extraction] for detail...

,direct_employment,indirect_employment,total_employment,direct_output,indirect_output,total_output,direct_GDP,indirect_GDP,total_GDP,government_revenue
sum,8995.738042,17779.764975,26775.503016,-6.694680e+09,-5.254192e+09,-1.194887e+10,-1.816362e+09,-2.513124e+09,-4.329486e+09,-4.278847e+08
mean,264.580531,522.934264,787.514795,-1.969023e+08,-1.545351e+08,-3.514374e+08,-5.342242e+07,-7.391542e+07,-1.273378e+08,-1.258485e+07
std,51.021044,100.841327,151.862371,5.793346e+07,4.546798e+07,1.034014e+08,1.571818e+07,2.174771e+07,3.746589e+07,3.702768e+06
max,294.886845,582.833645,877.720490,-1.242339e+08,-9.750262e+07,-2.217365e+08,-3.370644e+07,-4.663632e+07,-8.034276e+07,-7.940304e+06
min,128.145108,253.274371,381.419479,-3.133022e+08,-2.458892e+08,-5.591914e+08,-8.500336e+07,-1.176109e+08,-2.026142e+08,-2.002444e+07

## 3.6 Scanario6:  FM1 Higher utilization + HWP1 Longer-lived wood products

In [29]:
(FM1_OUTPUT_SUMMARY + HWP1_OUTPUT_SUMMARY).iloc[[0,1,3,4],:]

,direct_employment,indirect_employment,total_employment,direct_output,indirect_output,total_output,direct_GDP,indirect_GDP,total_GDP,government_revenue
sum,-54762.361101,-2139.445511,-56901.806612,-3.985126e+10,-2.406533e+10,-6.391659e+10,-1.370371e+10,-1.184623e+10,-2.554994e+10,-1.786063e+09
mean,-1610.657679,-62.924868,-1673.582547,-1.172096e+09,-7.078038e+08,-1.879900e+09,-4.030504e+08,-3.484184e+08,-7.514688e+08,-5.253125e+07
max,-780.094821,-30.476596,-810.571417,-6.640218e+08,-4.173677e+08,-1.081389e+09,-2.217664e+08,-2.044535e+08,-4.262199e+08,-3.149114e+07
min,-1795.150081,-70.132582,-1865.282663,-1.498205e+09,-9.386211e+08,-2.436826e+09,-5.015672e+08,-4.599364e+08,-9.615036e+08,-7.074311e+07

## 3.7 Scanario7: FM2 Harvest less + HWP1 Longer-lived wood products

In [30]:
(FM2_OUTPUT_SUMMARY + HWP1_OUTPUT_SUMMARY).iloc[[0,1,3,4],:]

,direct_employment,indirect_employment,total_employment,direct_output,indirect_output,total_output,direct_GDP,indirect_GDP,total_GDP,government_revenue
sum,-27359.615125,-8487.720795,-35847.335920,-1.949504e+10,-1.269821e+10,-3.219325e+10,-6.395052e+09,-6.098565e+09,-1.249362e+10,-9.318369e+08
mean,-804.694563,-249.638847,-1054.333409,-5.733836e+08,-3.734767e+08,-9.468604e+08,-1.880898e+08,-1.793696e+08,-3.674593e+08,-2.740697e+07
max,-389.333546,-224.497104,-613.935722,-2.623873e+08,-1.881048e+08,-4.504921e+08,-7.945665e+07,-8.918144e+07,-1.686381e+08,-1.418101e+07
min,-896.967136,-280.613062,-1177.474238,-8.197600e+08,-5.501305e+08,-1.369891e+09,-2.629564e+08,-2.626126e+08,-5.255690e+08,-4.055280e+07

## 3.8 Scanario8: FM3 Harvest residues for bioenergyigher + HWP1 Longer-lived wood products

In [31]:
(FM3_OUTPUT_SUMMARY + HWP1_OUTPUT_SUMMARY).iloc[[0,1,3,4],:]

,direct_employment,indirect_employment,total_employment,direct_output,indirect_output,total_output,direct_GDP,indirect_GDP,total_GDP,government_revenue
sum,26747.721450,338077.892666,364825.614116,-1.987793e+10,-1.200474e+10,-3.188267e+10,-6.835507e+09,-5.909920e+09,-1.274543e+10,-8.907551e+08
mean,786.697690,9943.467431,10730.165121,-5.846451e+08,-3.530806e+08,-9.377257e+08,-2.010443e+08,-1.738212e+08,-3.748655e+08,-2.619868e+07
max,1989.548510,11834.280555,13823.829065,-3.310787e+08,-2.081380e+08,-5.392167e+08,-1.105637e+08,-1.019689e+08,-2.125326e+08,-1.570108e+07
min,-575.004095,4124.922663,3549.918568,-7.454588e+08,-4.671771e+08,-1.212636e+09,-2.495346e+08,-2.289603e+08,-4.784949e+08,-3.519767e+07

## 3.9 Scanario9: FM4 Restricted harvest + HWP1 Longer-lived wood products

In [32]:
(FM4_OUTPUT_SUMMARY + HWP1_OUTPUT_SUMMARY).iloc[[0,1,3,4],:]

,direct_employment,indirect_employment,total_employment,direct_output,indirect_output,total_output,direct_GDP,indirect_GDP,total_GDP,government_revenue
sum,-27315.014162,-23826.885405,-51141.899567,-1.773257e+10,-1.337053e+10,-3.110310e+10,-5.190924e+09,-6.149051e+09,-1.133998e+10,-9.733006e+08
mean,-803.382769,-700.790747,-1504.173517,-5.215462e+08,-3.932508e+08,-9.147970e+08,-1.526742e+08,-1.808544e+08,-3.335287e+08,-2.862649e+07
max,-386.937242,-15.238271,-405.285681,-1.866043e+07,-1.199549e+08,-1.386153e+08,3.244572e+07,-4.455927e+07,-1.211355e+07,-9.300857e+06
min,-897.575040,-1104.794196,-1999.259067,-8.307508e+08,-5.880977e+08,-1.418848e+09,-2.560536e+08,-2.757576e+08,-5.318112e+08,-4.314413e+07

## 3.10 Scanario10 FM1&3-BASE: FM1 Higher utilization + FM3 Harvest residues for bioenergyigher

In [33]:
(FM1_OUTPUT_SUMMARY + FM3_OUTPUT_SUMMARY).iloc[[0,1,3,4],:]

,direct_employment,indirect_employment,total_employment,direct_output,indirect_output,total_output,direct_GDP,indirect_GDP,total_GDP,government_revenue
sum,26747.721450,338077.892666,364825.614116,-1.997333e+10,-1.206059e+10,-3.203392e+10,-6.868206e+09,-5.936305e+09,-1.280451e+10,-8.953075e+08
mean,786.697690,9943.467431,10730.165121,-5.874508e+08,-3.547233e+08,-9.421740e+08,-2.020061e+08,-1.745972e+08,-3.766033e+08,-2.633257e+07
max,1989.548510,11834.280555,13823.829065,-3.329431e+08,-2.092297e+08,-5.421727e+08,-1.112028e+08,-1.024846e+08,-2.136874e+08,-1.579006e+07
min,-575.004095,4124.922663,3549.918568,-7.527463e+08,-4.714440e+08,-1.224190e+09,-2.520326e+08,-2.309760e+08,-4.830087e+08,-3.554545e+07

## 3.11 Scanario11 FM1&3-HWP1: FM1 Higher utilization + FM3 Harvest residues for bioenergyigher + HWP1 Longer-lived wood products

In [34]:
(FM1_OUTPUT_SUMMARY + FM3_OUTPUT_SUMMARY+ HWP1_OUTPUT_SUMMARY).iloc[[0,1,3,4],:]

,direct_employment,indirect_employment,total_employment,direct_output,indirect_output,total_output,direct_GDP,indirect_GDP,total_GDP,government_revenue
sum,-633.459101,337008.169911,336374.710810,-3.985126e+10,-2.406533e+10,-6.391659e+10,-1.370371e+10,-1.184623e+10,-2.554994e+10,-1.786063e+09
mean,-18.631150,9912.004997,9893.373847,-1.172096e+09,-7.078038e+08,-1.879900e+09,-4.030504e+08,-3.484184e+08,-7.514688e+08,-5.253125e+07
max,1599.501100,11819.042257,13418.543356,-6.640218e+08,-4.173677e+08,-1.081389e+09,-2.217664e+08,-2.044535e+08,-4.262199e+08,-3.149114e+07
min,-1472.579135,4089.856372,2617.277237,-1.498205e+09,-9.386211e+08,-2.436826e+09,-5.015672e+08,-4.599364e+08,-9.615036e+08,-7.074311e+07

### 3.11 Final result saved to Excel file

In [24]:
summary_columns = ['Direct Employment','Employment in BC','Annual Forest Sector GDP','Annual Provincial GDP','Annual Government Revenue']
summary_columns

['Direct Employment',
 'Employment in BC',
 'Annual Forest Sector GDP',
 'Annual Provincial GDP',
 'Annual Government Revenue']

['Direct Employment','Employment in BC','Annual Forest Sector GDP','Annual Provincial GDP','Annual Government Revenue']

are the summary columns.

In [4]:
FM1_summary = [1,2,3,4,5]
FM2_summary = [1,2,3,4,5]
FM3_summary = [1,2,3,4,5]
FM4_summary = [1,2,3,4,5]
HWP1_summary = [1,2,3,4,5]
FM1N3_summary = [1,2,3,4,5]
FM1_HWP1_summary = [1,2,3,4,5]
FM2_HWP1_summary = [1,2,3,4,5]
FM3_HWP1_summary = [1,2,3,4,5]
FM1N3_HWP1_summary = [1,2,3,4,5]
FM4_HWP1_summary = [1,2,3,4,5]
PORTFOLIO_summary = [1,2,3,4,5]
# FM1_summary = [1,2,3,4,5]
# FM1_summary = [1,2,3,4,5]
# FM1_summary = [1,2,3,4,5]
# FM1_summary = [1,2,3,4,5]
# FM1_summary = [1,2,3,4,5]

In [16]:
total_summary = [['Direct Employment','Employment in BC','Annual Forest Sector GDP','Annual Provincial GDP','Annual Government Revenue'], 
                    FM1_summary ,
                    FM2_summary,
                    FM3_summary,
                    FM4_summary,
                    HWP1_summary ,
                    FM1N3_summary ,
                    FM1_HWP1_summary,
                    FM2_HWP1_summary ,
                    FM3_HWP1_summary,
                    FM1N3_HWP1_summary ,
                    FM4_HWP1_summary ,
                    PORTFOLIO_summary]

headers = total_summary.pop(0) # gives the headers as list and leaves data

In [17]:
total_summary = pd.DataFrame(total_summary, columns=headers)
total_summary

,Direct Employment,Employment in BC,Annual Forest Sector GDP,Annual Provincial GDP,Annual Government Revenue
0,1,2,3,4,5
1,1,2,3,4,5
2,1,2,3,4,5
3,1,2,3,4,5
4,1,2,3,4,5
5,1,2,3,4,5
6,1,2,3,4,5
7,1,2,3,4,5
8,1,2,3,4,5
9,1,2,3,4,5
10,1,2,3,4,5
11,1,2,3,4,5

In [21]:
total_summary.iloc[0,0]

1

In [23]:
import openpyxl

summary_file = 'summary.xlsx'
srcfile = openpyxl.load_workbook(summary_file,read_only=False, keep_vba= False)
#to open the excel sheet and if it has macros with keep_vba False

sheet_name = 'Results Summary'
srcsheet = srcfile[sheet_name] #get sheetname from the file

#srcsheet['B16']= str('write something') #write something in B16 cell of the supplied sheet
startrow = 5
startcol = 2
totalcol = 5
totalrow = 12
for i in range(totalrow):
    for j in range(totalcol):
        srcsheet.cell(row=startrow+i,column=startcol+j).value = total_summary.iloc[i,j]    
        

#write to row 1,col 1 explicitly, this type of writing is useful to write something in loops

srcfile.save(summary_file)
#save it as a new file, the original file is untouched and here I am saving it as xlsm(m here denotes macros).

## 4. Reference <a name="ref"></a>

1. Horne, Garry. 2008 2004 British Columbia Provicial Economic Multipliers and How to Use Them

2.

## 5. Platform setup <a name="setup"></a>

The model is implement in jupyter notebook format which can be easily setup by using [Anaconda Distribution](https://www.anaconda.com/downloads). See [Install Python with Anaconda](https://www.youtube.com/watch?v=LrMOrMb8-3s) for more detail.

[Anaconda Distribution](https://www.anaconda.com/downloads) includes Python, the Jupyter Notebook, and other commonly used packages for scientific computing and data science. 

First, download Anaconda. We recommend downloading Anaconda’s latest Python 3 version.

Second, install the version of Anaconda which you downloaded, following the instructions on the download page.

Third, to run the notebook, run the following command at the Terminal (Mac/Linux) or Command Prompt (Windows):

```jupyter notebook```

When the notebook opens in your browser, you will see the Notebook Dashboard, which will show a list of the notebooks, files, and subdirectories in the directory where the notebook server was started. 


![](https://jupyter.readthedocs.io/en/latest/_images/tryjupyter_file.png)

See [Running the Notebook](https://jupyter.readthedocs.io/en/latest/running.html#running) for more details. Or see [Jupyter Notebook Tutorial: Introduction, Setup, and Walkthrough](https://www.youtube.com/watch?v=HW29067qVWk) for tips of using Jupyter Notebooks.

Codecademy provides a good introduction of [jupyter notebook](https://www.codecademy.com/articles/how-to-use-jupyter-notebooks) and [installation](https://www.codecademy.com/articles/install-python3).

### Sub paragraph <a name="subparagraph1"></a>
This is a sub paragraph, formatted in heading 3 style